### ISSUE TITLE
How to use with CPM?

### ISSUE THREAD

**Issue by paulocoutinhox** [simdsoft/yasio#411]
Hi,

How to use it with CPM - cmake package manager?

Thanks.

**Comment by halx99** [comment]
Directly try follow?:
```cmake
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

project(CPMExampleYAsio)

# ---- Create binary ----

add_executable(CPMExampleYAsio main.cpp)
target_compile_features(CPMExampleYAsio PRIVATE cxx_std_17)

# ---- Dependencies ----

include(../../cmake/CPM.cmake)

CPMAddPackage(
  NAME yasio
  VERSION 4.0.0
  GITHUB_REPOSITORY "yasio/yasio"
  GIT_TAG "dev"
)

target_link_libraries(CPMExampleYAsio yasio yasio_http)

```

**Comment by paulocoutinhox** [comment]
Hi,

Nice, it is working.

There is only one problem, that is the headers outside yasio project required for yasio-httpclient:
https://github.com/yasio/yasio/blob/dev/extensions/yasio_http/HttpResponse.h#L36

Can you change to all headers be inside the yasio-httpclient?

Thanks.

**Comment by paulocoutinhox** [comment]
And the target_link_libraries is `target_link_libraries(CPMExampleYAsio PRIVATE yasio)`

**Comment by halx99** [comment]
The latest commits should works

**Comment by paulocoutinhox** [comment]
Im getting these errors:

```
3 warnings generated.
[ 98%] Linking CXX static library ../../libyasio.a
[ 98%] Built target yasio
[ 99%] Building CXX object CMakeFiles/test.dir/main-yasio.cpp.o
/Users/paulo/Developer/workspaces/cpp/yasio/main-yasio.cpp:5:10: fatal error: 'yasio_http/HttpClient.h' file not found
#include "yasio_http/HttpClient.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/test.dir/main-yasio.cpp.o] Error 1
make[1]: *** [CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
```

File: CMakeLists.txt

```
set(YASIO_VERSION dev)

CPMAddPackage(
  NAME yasio
  GITHUB_REPOSITORY yasio/yasio
  GIT_TAG ${YASIO_VERSION}
  OPTIONS
        "YASIO_SSL_BACKEND 2"
        "YASIO_BUILD_WITH_LUA NO"
        "YASIO_BUILD_WITH_CCLUA NO"
        "YASIO_BUILD_TESTS NO"
        "YASIO_BUILD_LUA_EXAMPLE NO"
        "YAISO_BUILD_NI NO"
)

add_executable(test main-yasio.cpp)

target_link_libraries(test yasio)
target_link_libraries(test mbedtls)
```

File: main-yasio.cpp

```
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

#include "yasio_http/HttpClient.h"
#include "yasio/yasio.hpp"

#include <fstream>

using namespace yasio;
using namespace yasio_ext::network;

#define CHROME_UA "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

void yasioTest()
{
  auto httpClient = HttpClient::getInstance();
  httpClient->setDispatchOnWorkThread(true);

  auto request = new HttpRequest();

  request->setHeaders(std::vector<std::string>{CHROME_UA});
  request->setUrl("https://github.com/yasio");
  request->setRequestType(HttpRequest::Type::Get);

  auto response = httpClient->sendSync(request);
  request->release();

  if (response)
  {
    if (response->getResponseCode() == 200)
    {
      auto responseData = response->getResponseData();
      // fwrite(responseData->data(), responseData->size(), 1, stdout);
      printf("===>request succeed\n");
    }
    else
      printf("===>request failed with %d\n", response->getResponseCode());
    printf("%s", "===>response headers:\n");
    for (auto& header : response->getResponseHeaders())
      printf("\t%s: %s\n", header.first.c_str(), header.second.c_str());
    response->release();
  }
  HttpClient::destroyInstance();
}

int main(int, char**)
{
#if defined(_WIN32)
  SetConsoleOutputCP(CP_UTF8);
#endif

  yasioTest();

  return 0;
}
```

**Comment by halx99** [comment]
do you clean your build directory?

**Comment by paulocoutinhox** [comment]
I updated the issue above ^

**Comment by halx99** [comment]
should link as follow
```cmake
target_link_libraries(CPMExampleYAsio yasio yasio_http)
```

**Comment by paulocoutinhox** [comment]
Same error:

```
[ 98%] Linking CXX static library ../../libyasio.a
[ 98%] Built target yasio
[ 99%] Building CXX object CMakeFiles/test.dir/main-yasio.cpp.o
/Users/paulo/Developer/workspaces/cpp/yasio/main-yasio.cpp:5:10: fatal error: 'yasio_http/HttpClient.h' file not found
#include "yasio_http/HttpClient.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/test.dir/main-yasio.cpp.o] Error 1
make[1]: *** [CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
```

```
add_executable(test main-yasio.cpp)
target_link_libraries(test yasio yasio_http)
target_link_libraries(test mbedtls)
```

**Comment by halx99** [comment]
The public includes of target `yasio_http`  should be inherited by the `test` which is depends on it: https://github.com/yasio/yasio/blob/dev/CMakeLists.txt#L437

**Comment by paulocoutinhox** [comment]
I tried it, but the error is the same:

```
set(YASIO_VERSION dev)

CPMAddPackage(
  NAME yasio
  GITHUB_REPOSITORY yasio/yasio
  GIT_TAG ${YASIO_VERSION}
  OPTIONS
        "YASIO_SSL_BACKEND 2"
        "YASIO_BUILD_WITH_LUA NO"
        "YASIO_BUILD_WITH_CCLUA NO"
        "YASIO_BUILD_TESTS NO"
        "YASIO_BUILD_LUA_EXAMPLE NO"
        "YAISO_BUILD_NI NO"
)

add_executable(test main-yasio.cpp)
target_link_libraries(test yasio yasio_http)
target_link_libraries(test mbedtls)
target_include_directories(test PUBLIC "${YASIO_ROOT}/extensions")
```

Error:

```
[ 98%] Linking CXX static library ../../libyasio.a
[ 98%] Built target yasio
[ 99%] Building CXX object CMakeFiles/test.dir/main-yasio.cpp.o
/Users/paulo/Developer/workspaces/cpp/yasio/main-yasio.cpp:5:10: fatal error: 'yasio_http/HttpClient.h' file not found
#include "yasio_http/HttpClient.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/test.dir/main-yasio.cpp.o] Error 1
make[1]: *** [CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by paulocoutinhox** [comment]
I tried this:

```
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)") 
-- YASIO_ROOT=/Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791
-- CMAKE_CXX_COMPILER_ID=AppleClang
-- MSVC=, MSVC_IDE=
-- Building yasio with C++11 support
-- CMAKE_SYSTEM_NAME=Darwin
-- Build with mbedtls support
-- Found Python3: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (found version "3.9.6") found components: Interpreter 
-- CPM: Adding package yasio@ (dev at /Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791)
CMake Error at CMakeLists.txt:48 (message):
  --------------

```

But it is not defined. Log:

```
CMake Error at CMakeLists.txt:48 (message):
  --------------
```

The variable `YASIO_ROOT` is not defined.

**Comment by paulocoutinhox** [comment]
The variable `YASIO_ROOT` it defined in your CMakeLists.txt but is not visible to me.

**Comment by paulocoutinhox** [comment]
Maybe YASIO_ROOT need some flag to be visible outside your lib.

**Comment by halx99** [comment]
You don't needs use it, because cmake will auto inherit include paths from target `yasio_http` for your `test` target

**Comment by paulocoutinhox** [comment]
Yes, this need work if everything is ok `target_link_libraries(test yasio yasio_http)`, but it is not working.

**Comment by paulocoutinhox** [comment]
Hi,

I made a project to you see and test with me to try fix it:
https://github.com/paulocoutinhox/cpp-http-test

**Comment by halx99** [comment]
I just test and works:
```cmake
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

project(CPMExampleYAsio)

# ---- Create binary ----

add_executable(CPMExampleYAsio main.cpp)
target_compile_features(CPMExampleYAsio PRIVATE cxx_std_17)

# ---- Dependencies ----

include(../../cmake/CPM.cmake)

CPMAddPackage(
  NAME yasio
  VERSION 4.0.0
  GITHUB_REPOSITORY "yasio/yasio"
  GIT_TAG "dev"
)

target_link_libraries(CPMExampleYAsio yasio_http)

```

main.cpp
```cpp
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

#include "yasio_http/HttpClient.h"
#include "yasio/yasio.hpp"

#include <fstream>

using namespace yasio;
using namespace yasio_ext::network;

#define CHROME_UA "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

void yasioTest()
{
  auto httpClient = HttpClient::getInstance();
  httpClient->setDispatchOnWorkThread(true);

  auto request = new HttpRequest();

  request->setHeaders(std::vector<std::string>{CHROME_UA});
  request->setUrl("https://github.com/yasio");
  request->setRequestType(HttpRequest::Type::Get);

  auto response = httpClient->sendSync(request);
  request->release();

  if (response)
  {
    if (response->getResponseCode() == 200)
    {
      auto responseData = response->getResponseData();
      // fwrite(responseData->data(), responseData->size(), 1, stdout);
      printf("===>request succeed\n");
    }
    else
      printf("===>request failed with %d\n", response->getResponseCode());
    printf("%s", "===>response headers:\n");
    for (auto& header : response->getResponseHeaders())
      printf("\t%s: %s\n", header.first.c_str(), header.second.c_str());
    response->release();
  }
  HttpClient::destroyInstance();
}

int main(int, char**)
{
#if defined(_WIN32)
  SetConsoleOutputCP(CP_UTF8);
#endif

  yasioTest();

  return 0;
}

```

**Comment by halx99** [comment]
> I tried it, but the error is the same:
> 
> ```
> set(YASIO_VERSION dev)
> 
> CPMAddPackage(
>   NAME yasio
>   GITHUB_REPOSITORY yasio/yasio
>   GIT_TAG ${YASIO_VERSION}
>   OPTIONS
>         "YASIO_SSL_BACKEND 2"
>         "YASIO_BUILD_WITH_LUA NO"
>         "YASIO_BUILD_WITH_CCLUA NO"
>         "YASIO_BUILD_TESTS NO"
>         "YASIO_BUILD_LUA_EXAMPLE NO"
>         "YAISO_BUILD_NI NO"
> )
> 
> add_executable(test main-yasio.cpp)
> target_link_libraries(test yasio yasio_http)
> target_link_libraries(test mbedtls)
> target_include_directories(test PUBLIC "${YASIO_ROOT}/extensions")
> ```
> 
> Error:
> 
> ```
> [ 98%] Linking CXX static library ../../libyasio.a
> [ 98%] Built target yasio
> [ 99%] Building CXX object CMakeFiles/test.dir/main-yasio.cpp.o
> /Users/paulo/Developer/workspaces/cpp/yasio/main-yasio.cpp:5:10: fatal error: 'yasio_http/HttpClient.h' file not found
> #include "yasio_http/HttpClient.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [CMakeFiles/test.dir/main-yasio.cpp.o] Error 1
> make[1]: *** [CMakeFiles/test.dir/all] Error 2
> make: *** [all] Error 2
> ```

Currently, the target `yasio_http` only build when `YASIO_BUILD_TESTS=TRUE`, will fix later

**Comment by halx99** [comment]
Done by https://github.com/yasio/yasio/commit/3c3f22f0bbe8268bf7b62eb3c592a164fb441fe4

**Comment by paulocoutinhox** [comment]
Hi,

It still have some problems.

I have disabled tests (https://github.com/paulocoutinhox/cpp-http-test/blob/main/CMakeLists.txt#L35-L42), but it still trying to build tests and because this throw error:

```
                                                 ^
/Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/tests/ssl/main.cpp:7:10: fatal error: 'sslcerts.hpp' file not found
#include "sslcerts.hpp"
         ^~~~~~~~~~~~~~
3 warnings and 1 error generated.
make[2]: *** [_deps/yasio-build/tests/ssl/CMakeFiles/ssltest.dir/main.cpp.o] Error 1
make[1]: *** [_deps/yasio-build/tests/ssl/CMakeFiles/ssltest.dir/all] Error 2
```

Maybe because this:
https://github.com/yasio/yasio/blob/dev/CMakeLists.txt#L448-L455

**Comment by halx99** [comment]
Fixed.

**Comment by paulocoutinhox** [comment]
Some warnings when use Xcode 14.3:

```
In file included from /Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/core/io_service.hpp:49:
/Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/core/xxsocket.hpp:511:18: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
            n += sprintf(buf + n, ":%u", (unsigned int)p);
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
In file included from /Users/paulo/Developer/workspaces/cpp/cpp-http-test/main-yasio.cpp:6:
In file included from /Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/yasio.hpp:33:
In file included from /Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/core/io_service.hpp:49:
/Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/core/xxsocket.hpp:544:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(snum, "%u", addr_bytes[idx]);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
In file included from /Users/paulo/Developer/workspaces/cpp/cpp-http-test/main-yasio.cpp:6:
In file included from /Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/yasio.hpp:33:
In file included from /Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/core/io_service.hpp:49:
/Users/paulo/.cache/CPM/yasio/dc0d657062bd19df2067839b324a8b1bb0c87791/yasio/core/xxsocket.hpp:1080:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
      sprintf(buffer, "%u", port); // It's enough for unsigned short, so use sprintf ok.
      ^
```

Another problem, it is compiling the extension `kcp`:

```
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: libyasio_kcp.a the table of contents is empty (no object file members in the library define global symbols)
[100%] Built target yasio_kcp
```

**Comment by paulocoutinhox** [comment]
Can you fix the warnings?

Can you create one configuration for each extension instead of add everything? Example:

```
YASIO_BUILD_EXT_HTTP
YASIO_BUILD_EXT_KCP
```

Instead of only:

```
YASIO_BUILD_EXTS
```

**Comment by halx99** [comment]
> Can you fix the warnings?
> 
> Can you create one configuration for each extension instead of add everything? Example:
> 
> ```
> YASIO_BUILD_EXT_HTTP
> YASIO_BUILD_EXT_KCP
> ```
> 
> Instead of only:
> 
> ```
> YASIO_BUILD_EXTS
> ```

done: https://github.com/yasio/yasio/commit/5baf6b7f67d325a9c1bf64e695345b4dac7bba42

**Comment by paulocoutinhox** [comment]
Thanks, it is working fine now.

The warnings will be fixed?

**Comment by paulocoutinhox** [comment]
Hi,

I see that you remove the use of sprintf and i test it now from dev branch and it is working without problems.

Thanks.
